Repository LaughLax/icarus5, pull requests merged in 2022-01, with the labels that each got.

#47 Catch more user `.send()`s
  modules/bank.js
  modules/bookmark.js
Labels: bug

#46 Testing guide and configuration file changes
  .gitignore
  config/config-example.json
  config/google-api-example.json
  config/rankConfig-example.json
  config/snowflakes-example.json
  contributing.md
  data/banned-example.json
  modules/01-events.js
  modules/01-filter.js
  modules/01-mods.js
  modules/bank.js
  modules/bookmark.js
  modules/botAdmin.js
  modules/rank.js
  utils/dbModels.js
Labels: documentation, enhancement

#51 Cake days
  config/snowflakes-example.json
  data/birthday.json
  models/Ign.model.js
  modules/cake.js
  utils/dbModels.js
Labels: enhancement

#63 Add `/mod fullinfo`, and fix #38.
  modules/01-filter.js
  modules/01-mods.js
  registry/mod.json
Labels: bug, enhancement

#64 Create and use utils/perms.js
  modules/01-mods.js
  modules/botAdmin.js
  utils/perms.js
Labels: style

#33 Call the error handler properly in bank.js
  modules/bank.js
Labels: bug

#58 Restructure database controller files
  config/config-example.json
  database/controllers/bank.js
  database/controllers/ign.js
  database/controllers/infraction.js
  database/controllers/user.js
  database/dbControllers.js
  database/models/Bank.model.js
  database/models/Ign.model.js
  database/models/Infraction.model.js
  database/models/User.model.js
  utils/dbModels.js
Labels: style

#71 Fix Issue 67 (bug in `warnCard()`)
  modules/01-filter.js
Labels: bug

#72 Don't apply color roles for cake days
  modules/cake.js
Labels: bug

#70 Fix references in db.user to other DB functions
  database/controllers/user.js
Labels: bug

#65 Add VSCode debug configuration
  .vscode/launch.json
Labels: documentation, enhancement

#78 Apply and remove roles at the same time
  modules/cake.js
Labels: bug

#75 Change, fixes #74
  modules/bank.js
Labels: bug

#84 Remove hierarchy check from `/mod mute` and `/mod office`
  modules/01-mods.js
Labels: bug

#83 Clean bank transactions
  config/snowflakes-example.json
  modules/bank.js
Labels: enhancement

#85 Move text to embed description
  modules/01-mods.js
Labels: bug

#91 Pass object to setFooter instead of string
  modules/01-events.js
  modules/01-filter.js
  modules/rank.js
Labels: question
